site :opscode

cookbook 'apt'
cookbook 'build-essential'
cookbook 'elasticsearch'
cookbook 'java'
cookbook 'logrotate'
cookbook 'mongodb', git: 'git://github.com/edelight/chef-mongodb.git', tag: '0.15.0'
cookbook 'nginx'
cookbook 'ntp'
cookbook 'openssh'
cookbook 'postfix'
cookbook 'postgresql'
cookbook 'rbenv'
cookbook 'redisio'
cookbook 'sudo'
cookbook 'swap'
cookbook 'unattended-upgrades'
cookbook 'user'
cookbook 'vim'
cookbook 'site-ruby', path: 'site-cookbooks/site-ruby'
cookbook 'site-user', path: 'site-cookbooks/site-user'
cookbook 'site-sqlite', path: 'site-cookbooks/site-sqlite'
cookbook 'site-libv8', path: 'site-cookbooks/site-libv8'
