site :opscode

cookbook 'apt'
cookbook 'build-essential'
cookbook 'logrotate'
cookbook 'mongodb-10gen'
cookbook 'nginx'
cookbook 'ntp'
cookbook 'openssh'
cookbook 'postfix'
cookbook 'postgresql'
cookbook 'rbenv'
cookbook 'sudo'
cookbook 'unattended_upgrades'
cookbook 'user'
cookbook 'vim'
cookbook 'site-ruby', path: 'site-cookbooks/site-ruby'
cookbook 'site-user', path: 'site-cookbooks/site-user'
cookbook 'site-sqlite', path: 'site-cookbooks/site-sqlite'
